[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'    # Solidity compiler version
optimizer = true           # Enable optimizer
optimizer_runs = 200       # Optimizer runs
evm_version = 'cancun'   # EVM version
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
